-- Additive upgrade for existing Oracle 11.2 portal schemas.
-- No DROP, DELETE, UPDATE or sequence reset.
alter table portal_employee add (extension_number varchar2(30 char));
alter table portal_employee add (job_description varchar2(500 char));
alter table portal_notification add (target_path varchar2(200 char));
create table portal_amendment (end_date date, start_date date, approver_id number(19,0) not null, created_at timestamp(9) not null, employee_id number(19,0) not null, id number(19,0) not null, original_version number(19,0) not null, replacement_id number(19,0), request_id number(19,0) not null, reviewed_at timestamp(9), reviewer_id number(19,0), source_attendance_version number(19,0), version number(19,0) not null, action varchar2(20 char) not null, leave_kind varchar2(20 char), request_type varchar2(20 char) not null, status varchar2(20 char) not null, review_comment varchar2(500 char), reason varchar2(1000 char) not null, original_summary varchar2(2000 char) not null, end_time varchar2(255 char), start_time varchar2(255 char), primary key (id));
create table portal_document (amount number(15,2), current_step number(10,0) not null, end_date date, start_date date, author_id number(19,0) not null, created_at timestamp(9) not null, id number(19,0) not null, version number(19,0) not null, kind varchar2(20 char) not null, status varchar2(20 char) not null, title varchar2(160 char) not null, content clob not null, primary key (id));
create table portal_document_step (step_order number(10,0) not null, document_id number(19,0) not null, id number(19,0) not null, reviewed_at timestamp(9), reviewer_id number(19,0) not null, version number(19,0) not null, status varchar2(20 char) not null, review_comment varchar2(500 char), primary key (id));
create table portal_file (created_at timestamp(9) not null, file_size number(19,0) not null, id number(19,0) not null, owner_id number(19,0) not null, uploader_id number(19,0) not null, version number(19,0) not null, owner_type varchar2(20 char) not null, filename varchar2(200 char) not null, data blob not null, primary key (id));
create table portal_holiday (holiday_date date not null unique, author_id number(19,0) not null, created_at timestamp(9) not null, id number(19,0) not null, version number(19,0) not null, kind varchar2(20 char) not null, name varchar2(120 char) not null, primary key (id));
create table portal_library (author_id number(19,0) not null, created_at timestamp(9) not null, id number(19,0) not null, updated_at timestamp(9) not null, version number(19,0) not null, visibility varchar2(20 char) not null, department varchar2(80 char) not null, title varchar2(160 char) not null, content clob not null, primary key (id));
create table portal_reservation (created_at timestamp(9) not null, employee_id number(19,0) not null, ends_at timestamp(9) not null, id number(19,0) not null, resource_id number(19,0) not null, starts_at timestamp(9) not null, version number(19,0) not null, status varchar2(20 char) not null, title varchar2(160 char) not null, primary key (id));
create table portal_resource (active number(10,0) not null check ((active in (0,1))), capacity number(10,0) not null, id number(19,0) not null, version number(19,0) not null, kind varchar2(20 char) not null, name varchar2(120 char) not null, location varchar2(200 char), primary key (id));
create table portal_task (due_date date not null, reminder_date date, assignee_id number(19,0) not null, created_at timestamp(9) not null, creator_id number(19,0) not null, id number(19,0) not null, version number(19,0) not null, status varchar2(20 char) not null, title varchar2(160 char) not null, description clob not null, primary key (id));
create table portal_task_comment (author_id number(19,0) not null, created_at timestamp(9) not null, id number(19,0) not null, task_id number(19,0) not null, version number(19,0) not null, content clob not null, primary key (id));
alter table portal_amendment add constraint FK8jvo9eye7i084s9613ylm6kq8 foreign key (approver_id) references portal_employee;
alter table portal_amendment add constraint FKmxdojmv8sd5f1t916dpjpr0f foreign key (employee_id) references portal_employee;
alter table portal_amendment add constraint FK2r16maqq54b0qpbkrjn46yq4c foreign key (reviewer_id) references portal_employee;
alter table portal_document add constraint FK1j23ifbbshp7hj9sxq2oliow7 foreign key (author_id) references portal_employee;
alter table portal_document_step add constraint FK89dgfaeka1hjaumjyqbd95d47 foreign key (document_id) references portal_document;
alter table portal_document_step add constraint FKn5ox64paoah0oxlk6lkv4a4pd foreign key (reviewer_id) references portal_employee;
alter table portal_file add constraint FKtonvjsyx6ve9lsftdqiecjg28 foreign key (uploader_id) references portal_employee;
alter table portal_holiday add constraint FK6qsyovyej99d4jj9443j43ghj foreign key (author_id) references portal_employee;
alter table portal_library add constraint FKphineosyy36a0h81m3cs65mec foreign key (author_id) references portal_employee;
alter table portal_reservation add constraint FKg91w4meh79lo0m1anm2vq8mgg foreign key (employee_id) references portal_employee;
alter table portal_reservation add constraint FKpvuxpr4op416u430upncql32p foreign key (resource_id) references portal_resource;
alter table portal_task add constraint FK1q3fh5iloj41w80s1rlaqkqud foreign key (assignee_id) references portal_employee;
alter table portal_task add constraint FK9msfd6gw9yn5xf5rdt0y3lgel foreign key (creator_id) references portal_employee;
alter table portal_task_comment add constraint FKiid63eeqgrq3bnfyka22napug foreign key (author_id) references portal_employee;
alter table portal_task_comment add constraint FKjylmdiwd5w4sw7a2s6ca5wylc foreign key (task_id) references portal_task;
create index ix_task_assignee_due on portal_task(assignee_id,due_date);
create index ix_document_author on portal_document(author_id,created_at);
create index ix_document_reviewer on portal_document_step(reviewer_id,status);
create index ix_file_owner on portal_file(owner_type,owner_id);
create index ix_reservation_time on portal_reservation(resource_id,starts_at,ends_at);
create index ix_amendment_request on portal_amendment(request_type,request_id,status);
create index ix_library_visibility on portal_library(visibility,department);